[package]
name = "ppm"
version = "0.1.0"
authors = ["Meelaay <elbaraka.amine@yahoo.com>", "ebr.ouadoud@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "embed"
crate-type = ["dylib"]